### PR TITLE
Add metric wiki for fluent-bit syslog plugin

### PR DESCRIPTION
**Pull request by dennyzhang**

### CODE REVIEW

**Comment by dennyzhang** [comment]
@wfernandes 

Currently it's a proposal to collect what metrics we might need to emit. If necessary, we can move it from code repo to github wiki.

We can talk about it after the regular daily standup

**Comment by dennyzhang** [comment]
@wfernandes , per our conversation, do you think we can merge the PR now?

**Comment by wfernandes** [comment]
I created [this chore](https://www.pivotaltracker.com/story/show/159018473) to instrument the plugin.

We can put the work of that chore in this branch and PR this documentation of the metrics along with the actual metrics implementation all at once. 

How does that sound?

**Comment by dennyzhang** [comment]
@wfernandes , sounds perfect to me. Thanks, man.

**Comment by dennyzhang** [comment]
Close this PR for now.

**Pull request closed without merging**
